// ============================================
// VentureAI — IdeaReport Component
// Displays the full AI-generated validation report
// Features: Share toggle, PDF export, Delete with confirm
// ============================================

"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Idea } from "@/types";
import {
  getRiskColor,
  getProfitabilityColor,
  getProfitabilityLabel,
  formatDate,
  copyToClipboard,
  generateShareUrl,
} from "@/lib/utils";
import toast from "react-hot-toast";
import {
  Share2,
  Download,
  Trash2,
  CheckCircle,
  XCircle,
  Users,
  Globe,
  Zap,
  Code,
  Shield,
  TrendingUp,
  AlertTriangle,
  Loader2,
  Lock,
  Unlock,
  Copy,
} from "lucide-react";

interface IdeaReportProps {
  idea: Idea;
}

export default function IdeaReport({ idea: initialIdea }: IdeaReportProps) {
  const [idea, setIdea] = useState(initialIdea);
  const [isDeleting, setIsDeleting] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [isTogglingShare, setIsTogglingShare] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const router = useRouter();

  // ---- Share Toggle ----
  const handleShareToggle = async () => {
    setIsTogglingShare(true);
    try {
      const res = await fetch(`/api/ideas/${idea.id}/share`, {
        method: "PATCH",
      });
      const result = await res.json();

      if (!result.success) throw new Error(result.error);

      setIdea((prev) => ({ ...prev, is_public: result.data.is_public }));

      if (result.data.is_public) {
        // Copy share URL to clipboard automatically
        await copyToClipboard(generateShareUrl(idea.share_token));
        toast.success("Report is now public! Link copied to clipboard.");
      } else {
        toast.success("Report is now private.");
      }
    } catch {
      toast.error("Failed to update share settings.");
    } finally {
      setIsTogglingShare(false);
    }
  };

  // ---- Copy Share Link ----
  const handleCopyLink = async () => {
    const success = await copyToClipboard(generateShareUrl(idea.share_token));
    if (success) toast.success("Share link copied!");
  };

  // ---- PDF Export ----
  const handleExport = async () => {
    setIsExporting(true);
    try {
      // Dynamic import to avoid SSR issues
      const { default: jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

      const margin = 20;
      let y = margin;
      const pageWidth = 210;
      const contentWidth = pageWidth - margin * 2;

      // Helper to add wrapped text and advance y
      const addText = (text: string, fontSize: number, isBold = false, color: [number, number, number] = [226, 232, 240]) => {
        doc.setFontSize(fontSize);
        doc.setFont("helvetica", isBold ? "bold" : "normal");
        doc.setTextColor(...color);
        const lines = doc.splitTextToSize(text, contentWidth);
        lines.forEach((line: string) => {
          if (y > 270) { doc.addPage(); y = margin; }
          doc.text(line, margin, y);
          y += fontSize * 0.4;
        });
        y += 3;
      };

      // Dark background
      doc.setFillColor(5, 6, 10);
      doc.rect(0, 0, 210, 297, "F");

      // Header accent bar
      doc.setFillColor(155, 89, 208);
      doc.rect(0, 0, 210, 3, "F");

      y = 15;
      addText("VentureAI", 10, false, [155, 89, 208]);
      addText("Startup Validation Report", 22, true, [255, 255, 255]);
      addText(idea.title, 16, true, [0, 212, 255]);
      addText(`Generated on ${formatDate(idea.created_at)}`, 9, false, [100, 116, 139]);
      y += 5;

      // Scores row
      addText(`Profitability Score: ${idea.profitability}/100  |  Risk Level: ${idea.risk_level}`, 11, true, [226, 232, 240]);
      y += 5;

      const sections: { title: string; content: string }[] = [
        { title: "Problem Summary", content: idea.problem ?? "" },
        { title: "Customer Persona", content: idea.customer ?? "" },
        { title: "Market Overview", content: idea.market ?? "" },
        { title: "Competitors", content: (idea.competitor ?? []).map((c, i) => `${i + 1}. ${c.name}: ${c.differentiation}`).join("\n") },
        { title: "Recommended Tech Stack", content: (idea.tech_stack ?? []).join(", ") },
        { title: "Justification", content: idea.justification ?? "" },
      ];

      sections.forEach(({ title, content }) => {
        addText(title, 13, true, [155, 89, 208]);
        addText(content, 10, false, [148, 163, 184]);
        y += 4;
      });

      addText("Generated by VentureAI · ventureai.vercel.app", 8, false, [71, 85, 105]);

      doc.save(`ventureai-${idea.title.toLowerCase().replace(/\s+/g, "-")}.pdf`);
      toast.success("PDF downloaded!");
    } catch (err) {
      console.error("PDF export error:", err);
      toast.error("Failed to export PDF.");
    } finally {
      setIsExporting(false);
    }
  };

  // ---- Delete ----
  const handleDelete = async () => {
    setIsDeleting(true);
    try {
      const res = await fetch(`/api/ideas/${idea.id}`, { method: "DELETE" });
      const result = await res.json();
      if (!result.success) throw new Error(result.error);
      toast.success("Idea deleted.");
      router.push("/dashboard");
    } catch {
      toast.error("Failed to delete idea.");
      setIsDeleting(false);
      setShowDeleteModal(false);
    }
  };

  // ---- Status guard: non-completed ideas ----
  if (idea.status !== "completed") {
    return (
      <div className="glass rounded-2xl p-10 text-center">
        <div className={`w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-4 ${
          idea.status === "failed"
            ? "bg-[rgba(239,68,68,0.1)] border border-[rgba(239,68,68,0.2)]"
            : "bg-[rgba(0,212,255,0.1)] border border-[rgba(0,212,255,0.2)]"
        }`}>
          {idea.status === "failed" ? (
            <XCircle className="w-8 h-8 text-[#ef4444]" />
          ) : (
            <Loader2 className="w-8 h-8 text-[#00d4ff] animate-spin" />
          )}
        </div>
        <h2 className="font-heading text-xl font-bold text-white mb-2">
          {idea.status === "failed" ? "Analysis Failed" : "Analysis In Progress"}
        </h2>
        <p className="text-slate-400 text-sm">
          {idea.status === "failed"
            ? "The AI analysis failed. Please try submitting your idea again."
            : "Your idea is being analyzed. This page will update when complete."}
        </p>
      </div>
    );
  }

  return (
    <>
      {/* ---- Report Header ---- */}
      <div className="mb-6 animate-fade-in">
        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 mb-6">
          <div>
            <h1 className="font-heading text-2xl sm:text-3xl font-bold text-white mb-2 leading-snug">
              {idea.title}
            </h1>
            <p className="text-slate-500 text-sm">
              Analyzed on {formatDate(idea.created_at)}
            </p>
          </div>

          {/* Action Buttons */}
          <div className="flex items-center gap-2 flex-shrink-0">
            {/* Share toggle */}
            <button
              onClick={handleShareToggle}
              disabled={isTogglingShare}
              title={idea.is_public ? "Make private" : "Make public & copy link"}
              className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium transition-all border ${
                idea.is_public
                  ? "text-[#00d4ff] bg-[rgba(0,212,255,0.1)] border-[rgba(0,212,255,0.2)] hover:bg-[rgba(0,212,255,0.2)]"
                  : "text-slate-400 bg-[rgba(255,255,255,0.04)] border-[rgba(255,255,255,0.08)] hover:text-white"
              }`}
            >
              {isTogglingShare ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : idea.is_public ? (
                <Unlock className="w-3.5 h-3.5" />
              ) : (
                <Lock className="w-3.5 h-3.5" />
              )}
              {idea.is_public ? "Public" : "Share"}
            </button>

            {/* Copy link (only when public) */}
            {idea.is_public && (
              <button
                onClick={handleCopyLink}
                title="Copy share link"
                className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium text-slate-400 bg-[rgba(255,255,255,0.04)] border border-[rgba(255,255,255,0.08)] hover:text-white transition-all"
              >
                <Copy className="w-3.5 h-3.5" />
                Copy Link
              </button>
            )}

            {/* Export PDF */}
            <button
              onClick={handleExport}
              disabled={isExporting}
              title="Export as PDF"
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium text-slate-400 bg-[rgba(255,255,255,0.04)] border border-[rgba(255,255,255,0.08)] hover:text-white transition-all"
            >
              {isExporting ? (
                <Loader2 className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <Download className="w-3.5 h-3.5" />
              )}
              Export
            </button>

            {/* Delete */}
            <button
              onClick={() => setShowDeleteModal(true)}
              title="Delete idea"
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium text-[#ef4444] bg-[rgba(239,68,68,0.05)] border border-[rgba(239,68,68,0.15)] hover:bg-[rgba(239,68,68,0.1)] transition-all"
            >
              <Trash2 className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

        {/* Score Summary Bar */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {/* Profitability Score */}
          <div className="glass rounded-xl p-4 col-span-2 sm:col-span-1">
            <p className="text-slate-500 text-xs mb-1">Profitability Score</p>
            <div className="flex items-end gap-2">
              <span className={`font-heading text-3xl font-bold ${getProfitabilityColor(idea.profitability)}`}>
                {idea.profitability}
              </span>
              <span className="text-slate-600 text-sm mb-1">/100</span>
            </div>
            <p className={`text-xs font-medium ${getProfitabilityColor(idea.profitability)}`}>
              {getProfitabilityLabel(idea.profitability)}
            </p>
          </div>

          {/* Profitability Bar visual */}
          <div className="glass rounded-xl p-4 col-span-2 sm:col-span-1 flex flex-col justify-between">
            <p className="text-slate-500 text-xs mb-2">Score Breakdown</p>
            <div className="w-full bg-[#1a1b2e] rounded-full h-2">
              <div
                className={`h-full rounded-full transition-all duration-1000 ${
                  (idea.profitability ?? 0) >= 70
                    ? "bg-[#10b981]"
                    : (idea.profitability ?? 0) >= 40
                    ? "bg-[#f59e0b]"
                    : "bg-[#ef4444]"
                }`}
                style={{ width: `${idea.profitability}%` }}
              />
            </div>
          </div>

          {/* Risk Level */}
          <div className={`rounded-xl p-4 border ${getRiskColor(idea.risk_level)}`}>
            <p className="text-xs opacity-70 mb-1">Risk Level</p>
            <div className="flex items-center gap-2">
              <Shield className="w-5 h-5" />
              <span className="font-heading font-bold text-lg">{idea.risk_level}</span>
            </div>
          </div>

          {/* Status */}
          <div className="glass rounded-xl p-4">
            <p className="text-slate-500 text-xs mb-1">Status</p>
            <div className="flex items-center gap-2 text-[#10b981]">
              <CheckCircle className="w-5 h-5" />
              <span className="font-heading font-bold text-lg">Validated</span>
            </div>
          </div>
        </div>
      </div>

      {/* ---- Report Sections ---- */}
      <div className="space-y-4">
        {/* Problem Summary */}
        <ReportSection
          icon={AlertTriangle}
          title="Problem Summary"
          iconColor="text-[#f59e0b]"
          iconBg="bg-[rgba(245,158,11,0.1)]"
          delay={0}
        >
          <p className="text-slate-300 leading-relaxed">{idea.problem}</p>
        </ReportSection>

        {/* Customer Persona */}
        <ReportSection
          icon={Users}
          title="Customer Persona"
          iconColor="text-[#9b59d0]"
          iconBg="bg-[rgba(155,89,208,0.1)]"
          delay={0.05}
        >
          <p className="text-slate-300 leading-relaxed">{idea.customer}</p>
        </ReportSection>

        {/* Market Overview */}
        <ReportSection
          icon={Globe}
          title="Market Overview"
          iconColor="text-[#00d4ff]"
          iconBg="bg-[rgba(0,212,255,0.1)]"
          delay={0.1}
        >
          <p className="text-slate-300 leading-relaxed">{idea.market}</p>
        </ReportSection>

        {/* Competitors */}
        <ReportSection
          icon={TrendingUp}
          title="Competitor Analysis"
          iconColor="text-[#10b981]"
          iconBg="bg-[rgba(16,185,129,0.1)]"
          delay={0.15}
        >
          <div className="space-y-3">
            {(idea.competitor ?? []).map((comp, index) => (
              <div
                key={index}
                className="flex gap-3 p-3 rounded-xl bg-[rgba(255,255,255,0.02)] border border-[rgba(255,255,255,0.05)]"
              >
                <div className="w-7 h-7 rounded-lg bg-[rgba(16,185,129,0.15)] flex items-center justify-center flex-shrink-0 mt-0.5">
                  <span className="text-[#10b981] text-xs font-bold">{index + 1}</span>
                </div>
                <div>
                  <p className="text-white font-semibold text-sm mb-0.5">{comp.name}</p>
                  <p className="text-slate-400 text-sm leading-relaxed">{comp.differentiation}</p>
                </div>
              </div>
            ))}
          </div>
        </ReportSection>

        {/* Tech Stack */}
        <ReportSection
          icon={Code}
          title="Recommended Tech Stack"
          iconColor="text-[#b47ee0]"
          iconBg="bg-[rgba(180,126,224,0.1)]"
          delay={0.2}
        >
          <div className="flex flex-wrap gap-2">
            {(idea.tech_stack ?? []).map((tech) => (
              <span
                key={tech}
                className="px-3 py-1.5 rounded-lg bg-[rgba(155,89,208,0.1)] border border-[rgba(155,89,208,0.2)] text-[#b47ee0] text-sm font-medium"
              >
                {tech}
              </span>
            ))}
          </div>
        </ReportSection>

        {/* Justification */}
        <ReportSection
          icon={Zap}
          title="AI Justification"
          iconColor="text-[#00d4ff]"
          iconBg="bg-[rgba(0,212,255,0.1)]"
          delay={0.25}
        >
          <p className="text-slate-300 leading-relaxed">{idea.justification}</p>
        </ReportSection>
      </div>

      {/* ---- Delete Confirmation Modal ---- */}
      {showDeleteModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fade-in">
          <div className="glass rounded-2xl p-8 max-w-sm w-full border border-[rgba(239,68,68,0.2)]">
            <div className="w-12 h-12 rounded-xl bg-[rgba(239,68,68,0.1)] border border-[rgba(239,68,68,0.2)] flex items-center justify-center mx-auto mb-4">
              <Trash2 className="w-6 h-6 text-[#ef4444]" />
            </div>
            <h3 className="font-heading text-xl font-bold text-white text-center mb-2">
              Delete this idea?
            </h3>
            <p className="text-slate-400 text-sm text-center mb-6">
              This will permanently delete &ldquo;{idea.title}&rdquo; and its AI report. This action cannot be undone.
            </p>
            <div className="flex gap-3">
              <button
                onClick={() => setShowDeleteModal(false)}
                disabled={isDeleting}
                className="flex-1 py-2.5 rounded-xl text-sm font-medium text-slate-400 bg-[rgba(255,255,255,0.04)] border border-[rgba(255,255,255,0.08)] hover:text-white transition-all"
              >
                Cancel
              </button>
              <button
                onClick={handleDelete}
                disabled={isDeleting}
                className="flex-1 py-2.5 rounded-xl text-sm font-semibold text-white bg-[#ef4444] hover:bg-[#dc2626] transition-all disabled:opacity-60 flex items-center justify-center gap-2"
              >
                {isDeleting ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Trash2 className="w-4 h-4" />
                )}
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

// ---- Reusable Report Section Wrapper ----
interface ReportSectionProps {
  icon: React.ElementType;
  title: string;
  iconColor: string;
  iconBg: string;
  delay?: number;
  children: React.ReactNode;
}

function ReportSection({ icon: Icon, title, iconColor, iconBg, delay = 0, children }: ReportSectionProps) {
  return (
    <div
      className="glass rounded-2xl p-6 border border-[rgba(155,89,208,0.08)] animate-fade-in-up"
      style={{ animationDelay: `${delay}s` }}
    >
      <div className="flex items-center gap-3 mb-4">
        <div className={`w-9 h-9 rounded-xl ${iconBg} flex items-center justify-center flex-shrink-0`}>
          <Icon className={`w-4.5 h-4.5 ${iconColor}`} />
        </div>
        <h2 className="font-heading font-semibold text-white">{title}</h2>
      </div>
      {children}
    </div>
  );
}